<a href="https://colab.research.google.com/github/Vishesh-Krishna-S-A/Nutriv/blob/main/Nutriv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nutriv Project

In [ ]:
import numpy as np
import pandas as pd

## Importing the dataset

In [ ]:
recipes = pd.read_csv('epi_r.csv')
X = recipes.iloc[:, 2:].values
y = recipes.iloc[:, 0].values

In [ ]:
print(X)

[[4.260e+02 3.000e+01 7.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [4.030e+02 1.800e+01 2.300e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.650e+02 6.000e+00 7.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.990e+02 3.000e+00 2.100e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.466e+03 1.200e+01 1.000e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.470e+02 1.000e+00 2.600e+01 ...       nan       nan       nan]]


In [ ]:
print(y)

['Lentil, Apple, and Turkey Wrap '
 'Boudin Blanc Terrine with Red Onion Confit '
 'Potato and Fennel Soup Hodge ' ... 'Almond Brown Butter '
 'Spiced Chocolate Torte Wrapped in Chocolate Ribbons ' 'Herbed Olives ']


In [ ]:
recipes = pd.read_csv('Nutriv.csv')
def filter_by_cal(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['breakfast'] >= 1)]

filter_C =filter_by_cal(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)

# Step 5: Print out the recommended recipes
print(recommended_recipe.loc[:, 'title':'breakfast'])

                                                   title  calories  protein  \
6018   Super Green Smoothie Bowl With Matcha and Ginger      505.0     10.0   
17508                Egg and Avocado Breakfast Sandwich      445.0     17.0   

        fat  sodium  #cakeweek  #wasteless  22-minute meals  \
6018   39.0    34.0          0           0                0   
17508  24.0   449.0          0           0                0   

       3-ingredient recipes  30 days of groceries  ...  bon appétit  \
6018                      0                     0  ...            0   
17508                     0                     0  ...            1   

       bon app��tit  boston  bourbon  braise  bran  brandy  bread  \
6018              0       0        0       0     0       0      0   
17508             0       0        0       0     0       0      0   

       breadcrumbs  breakfast  
6018             0          1  
17508            0          1  

[2 rows x 71 columns]


## Filtering based on Calories and Type of food

In [ ]:

def count():
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (88.362+(13.397*weight)+(4.799*height)-(5.677*age))*1.2
    print('Required calories with no exercise to lose weight:', (Calories- 500),' to ', (Calories-250),'kcal')
    print('Required calories with no exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with no exercise to increase weight:', (Calories+250),' to ', (Calories+500)kcal')


In [ ]:

def count2():
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (88.362+(13.397*weight)+(4.799*height)-(5.677*age))*1.55
    print('Required calories with moderate exercise to lose weight:', (Calories- 500),' to ', (Calories-250),'kcal')
    print('Required calories with moderate exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with moderate exercise to increase weight:', (Calories+250),' to ', (Calories+500),'kcal')


In [ ]:

def count3():
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (88.362+(13.397*weight)+(4.799*height)-(5.677*age))*1.725
    print('Required calories with hard exercise to lose weight:', (Calories- 500),' to ', (Calories-250),'kcal')
    print('Required calories with hard exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with hard exercise to increase weight:', (Calories+250),' to ', (Calories+500),'kcal')


In [ ]:

def count4():
    print('female')
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (447.593+(9.247*weight)+(3.098*height)-(4.330*age))*1.2
    print('Required calories with no exercise to lose weight:', (Calories - 500),' to ', (Calories-250),'kcal')
    print('Required calories with no exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with no exercise to increase weight:', (Calories+250),' to ', (Calories+500)kcal')


In [ ]:

def count5():
    print('female')
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (447.593+(9.247*weight)+(3.098*height)-(4.330*age))*1.55
    print('Required calories with moderate exercise to lose weight:', (Calories-500),' to ', (Calories-250),'kcal')
    print('Required calories with moderate exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with moderate exercise to increase weight:', (Calories+250),' to ', (Calories+500),'kcal')


In [ ]:

def count6():
    print('female')
    age = float(input('Age:\n'))
    weight = float(input('Weight:\n'))
    height = float(input('Height:\n'))
    Calories = (447.593+(9.247*weight)+(3.098*height)-(4.330*age))*1.725
    print('Required calories with hard exercise to lose weight:', (Calories-500),' to ', (Calories-250),'kcal')
    print('Required calories with hard exercise to maintain weight:', (Calories),' to ', (Calories+100),'kcal')
    print('Required calories with hard exercise to increase weight:', (Calories+250),' to ', (Calories+500),'kcal')


In [ ]:
#@title lunch selector
repes = pd.read_csv('Nutriv.csv')

def filter_by_cal_lunch(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['lunch'] >= 1)]

filter_C =filter_by_cal_lunch(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)
recommended_recipe = recommended_recipe[['title','calories','protein','fat', 'lunch']]
# Step 5: Print out the recommended recipes
print(recommended_recipe)

                                                   title  calories  protein  \
18302                     Crab Cakes with Avocado Salad      462.0     19.0   
12251  Pan-Grilled Salmon on Toast with Scallion Mayo...     457.0     27.0   

        fat  lunch  
18302  25.0      1  
12251  32.0      1  


In [ ]:
a=
b=


In [ ]:
import pandas as pd
import random

# Load the data into a pandas dataframe
df = pd.read_csv('Nutriv.csv')

# Define the range of the sum of the randomly selected values
min_sum = a
max_sum = b

# Select 5 random values from the numeric column
selected_values = []
while sum(selected_values) < min_sum or sum(selected_values) > max_sum:
    selected_values = random.sample(list(df['calories']), 5)

# Print the title values corresponding to the selected numeric values
for val in selected_values:
    print(df.loc[df['calories'] == val, 'title'].values[0])

Bacon Swiss Burgers with Tomato and Avocado 
Avocado and Grapefruit Salad 
Avocado, Shrimp, and Endive Salad 
Bavarian Cream with Raspberry Coulis 
Asparagus Soup with Basil Cream 


In [ ]:
a=
b=


In [ ]:
import pandas as pd
import random

# Load data from a CSV file
df = pd.read_csv('Nutriv.csv')

# Define the sum range
min_sum = 1000
max_sum = 2000

# Define a list to store the selected rows
selected_rows = []

# Loop until we find 5 rows that meet the criteria
while len(selected_rows) < 5:
    # Choose a random row index
    row_index = random.randint(0, len(df) - 1)
    
    # Check if the sum of the numeric column is in the range
    if min_sum <= df.iloc[row_index]['calories'] <= max_sum:
        
        # Check if the three binary columns have no ones at the same time
        if not (df.iloc[row_index]['breakfast'] == 1 and df.iloc[row_index]['lunch'] == 1 and df.iloc[row_index]['dinner'] == 1):
            
            # Add the row index to the selected_rows list
            selected_rows.append(row_index)

# Print the characters from the title column of the selected rows
for row_index in selected_rows:
    print(row_index)
    print(df.iloc[row_index]['title'])


1522
Chilean Country Ribs 
5501
Pork Shoulder with Mustard-Mushroom Gravy 
6826
Shrimp with Chunky Tomato-Saffron Sauce 
2111
Crispy Chicken with Shallots 
672
Bo Ssäm Grilled Pork and Pickled Slaw in Lettuce Cups 


In [ ]:
import pandas as pd
import random

# Load the data into a pandas DataFrame
df = pd.read_csv('Nutriv.csv')

# Define the range for the sum of the 5 random values
min_sum = a
max_sum = b

# Define the names of the columns with ones and zeros
col_names = ['lunch', 'breakfast', 'dinner']

# Loop until we find a valid set of rows
while True:
    # Select 5 random rows from the DataFrame
    rows = df.sample(n=5)

    # Calculate the sum of the numeric column for the selected rows
    numeric_sum = rows['calories'].sum()

    # Check if the sum is within the specified range
    if min_sum <= numeric_sum <= max_sum:
        # Check if only one of the columns with ones and zeros has a one
        ones_count = 0
        for col_name in col_names:
            if rows[col_name].sum() == 1:
                ones_count += 1
        if ones_count == 1:
            # Print the characters from the title column for the selected rows
            print(rows['title'].tolist())
            break

['Sweet-and-Sour Brussels Sprouts with Fresh Dill ', 'Salmon Consommé with Créme Fraîche and Salmon Caviar ', 'Indian-Style Chicken with Ginger and Curry ', 'Yogurt Marinated Chicken Skewers With Toum Garlic Sauce ', 'Grilled Chorizo, Goat Cheese, and Watercress Pita Pizzas ']


DECISION TREE TRAINING::


In [1]:

import numpy as np
import pandas as pd


from sklearn.tree import DecisionTreeClassifier
import random
data = pd.read_csv('Nutriv.csv')

# filter the dataset to include only breakfast, lunch, and dinner recipes
data = data[['calories', 'breakfast', 'lunch', 'dinner', 'title']]
data = data[data[['breakfast', 'lunch', 'dinner']].apply(lambda x: x.isin([0, 1]).all(), axis=1)]

# split the dataset into training and testing datasets
train_data = data.iloc[:80, :]
test_data = data.iloc[80:, :]

# create the decision tree model
features = ['calories', 'breakfast', 'lunch', 'dinner']
X_train = train_data[features]
y_train = train_data['calories']
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

# generate a random breakfast recipe with calories between 400 to 800
breakfast = random.randint(0, 1)
breakfast_calories = random.randint(400, 800)
breakfast_data = [[breakfast_calories, breakfast, 0, 0]]
breakfast_recipe = tree_model.predict(breakfast_data)[0]
breakfast_title = train_data[train_data['calories']==breakfast_recipe]['title'].iloc[0]

# generate a random lunch recipe with calories between 500 to 1000
lunch = random.randint(0, 1)
lunch_calories = random.randint(500, 1000)
lunch_data = [[lunch_calories, 0, lunch, 0]]
lunch_recipe = tree_model.predict(lunch_data)[0]
lunch_title = train_data[train_data['calories']==lunch_recipe]['title'].iloc[0]

# generate a random dinner recipe with calories between 600 to 1200
dinner = random.randint(0, 1)
dinner_calories = random.randint(600, 1200)
dinner_data = [[dinner_calories, 0, 0, dinner]]
dinner_recipe = tree_model.predict(dinner_data)[0]
dinner_title = train_data[train_data['calories']==dinner_recipe]['title'].iloc[0]

# calculate the total calories and check if they are between 1000 to 2000
total_calories = breakfast_calories + lunch_calories + dinner_calories
while total_calories < 1000 or total_calories > 2000:
    breakfast = random.randint(0, 1)
    breakfast_calories = random.randint(400, 800)
    breakfast_data = [[breakfast_calories, breakfast, 0, 0]]
    breakfast_recipe = tree_model.predict(breakfast_data)[0]
    breakfast_title = train_data[train_data['calories']==breakfast_recipe]['title'].iloc[0]
    lunch = random.randint(0, 1)
    lunch_calories = random.randint(500, 1000)
    lunch_data = [[lunch_calories, 0, lunch, 0]]
    lunch_recipe = tree_model.predict(lunch_data)[0]
    lunch_title = train_data[train_data['calories']==lunch_recipe]['title'].iloc[0]
    dinner = random.randint(0, 1)
    dinner_calories = random.randint(600, 1200)
    dinner_data = [[dinner_calories, 0, dinner, 0]]
    dinner_recipe = tree_model.predict(dinner_data)[0]
    dinner_title = train_data[train_data['calories']==dinner_recipe]['title'].iloc[0]
    total_calories = breakfast_calories + lunch_calories + dinner_calories

# print the selected recipes and their total calories
print(f"Breakfast recipe name: {breakfast_title}, {breakfast_recipe} calories")
print(f"Lunch recipe name: {lunch_title},{lunch_calories} calories)")
print(f"Dinner recipe: {dinner_title}, {dinner_calories} calories)")
print(f"Total calories: {total_calories}")



Breakfast recipe name: "Paella" Fried Rice , 505 calories
Lunch recipe name: African Adobo-Rubbed Tuna Steaks ,747 calories)
Dinner recipe: Almond-Crusted Salmon with Leek and Lemon Cream , 688 calories)
Total calories: 1920


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does 

In [4]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# load the dataset
data = pd.read_csv('Nutriv.csv')

# filter the dataset to include only breakfast, lunch, and dinner recipes
data = data[['calories', 'breakfast', 'lunch', 'dinner']]
data = data[data[['breakfast', 'lunch', 'dinner']].apply(lambda x: x.isin([0, 1]).all(), axis=1)]

# split the dataset into training and testing datasets
train_data = data.iloc[:80, :]
test_data = data.iloc[80:, :]

# create the decision tree model
features = ['calories', 'breakfast', 'lunch', 'dinner']
X_train = train_data[features]
y_train = train_data['dinner']
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

# test the model on the testing dataset and print the accuracy score
X_test = test_data[features]
y_test = test_data['dinner']
y_pred = tree_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)


Accuracy: 1.0


In [14]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import random

# load the dataset
data = pd.read_csv('Nutriv.csv')

# filter the dataset to include only breakfast, lunch, and dinner recipes
data = data[['calories', 'breakfast', 'lunch', 'dinner']]
data = data[data[['breakfast', 'lunch', 'dinner']].apply(lambda x: x.isin([0, 1]).all(), axis=1)]

# split the dataset into training and testing datasets
train_data = data.iloc[:80, :]
test_data = data.iloc[80:, :]

# create the decision tree model
features = ['calories', 'breakfast', 'lunch', 'dinner']
X_train = train_data[features]
y_train = train_data['calories']
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

# evaluate the accuracy of the model using the testing dataset
X_test = test_data[features]
y_test = test_data['calories']
y_pred = tree_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the decision tree model: {accuracy:.2f}")

# generate a random breakfast recipe with calories between 400 to 800
breakfast = random.randint(0, 1)
breakfast_calories = random.randint(400, 800)
breakfast_data = [[breakfast_calories, breakfast, 0, 0]]
breakfast_recipe = tree_model.predict(breakfast_data)[0]

# generate a random lunch recipe with calories between 500 to 1000
lunch = random.randint(0, 1)
lunch_calories = random.randint(500, 1000)
lunch_data = [[lunch_calories, 0, lunch, 0]]
lunch_recipe = tree_model.predict(lunch_data)[0]

# generate a random dinner recipe with calories between 600 to 1200
dinner = random.randint(0, 1)
dinner_calories = random.randint(600, 1200)
dinner_data = [[dinner_calories, 0, 0, dinner]]
dinner_recipe = tree_model.predict(dinner_data)[0]

# calculate the total calories and check if they are between 1000 to 2000
total_calories = breakfast_calories + lunch_calories + dinner_calories
while total_calories < 1000 or total_calories > 2000:
    breakfast = random.randint(0, 1)
    breakfast_calories = random.randint(400, 800)
    breakfast_data = [[breakfast_calories, breakfast, 0, 0]]
    breakfast_recipe = tree_model.predict(breakfast_data)[0]
    lunch = random.randint(0, 1)
    lunch_calories = random.randint(500, 1000)
    lunch_data = [[lunch_calories, 0, lunch, 0]]
    lunch_recipe = tree_model.predict(lunch_data)[0]
    dinner = random.randint(0, 1)
    dinner_calories = random.randint(600, 1200)
    dinner_data = [[dinner_calories, 0, 0, dinner]]
    dinner_recipe = tree_model.predict(dinner_data)[0]
    total_calories = breakfast_calories + lunch_calories + dinner_calories

# print the selected recipes and their total calories
print(f"Breakfast recipe name: {breakfast_title}, {breakfast_recipe} calories")
print(f"Lunch recipe name: {lunch_title},{lunch_calories} calories)")
print(f"Dinner recipe: {dinner_title}, {dinner_calories} calories)")
print(f"Total calories: {total_calories}")

Accuracy of the decision tree model: 0.05
Breakfast recipe name: "Paella" Fried Rice , 429 calories
Lunch recipe name: African Adobo-Rubbed Tuna Steaks ,711 calories)
Dinner recipe: Almond-Crusted Salmon with Leek and Lemon Cream , 685 calories)
Total calories: 1819


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
