<a href="https://colab.research.google.com/github/Vishesh-Krishna-S-A/Nutriv/blob/main/Nutriv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nutriv Project

In [ ]:
import numpy as np
import pandas as pd

## Importing the dataset

In [ ]:
recipes = pd.read_csv('epi_r.csv')
X = recipes.iloc[:, 2:].values
y = recipes.iloc[:, 0].values

In [ ]:
print(X)

[[4.260e+02 3.000e+01 7.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [4.030e+02 1.800e+01 2.300e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.650e+02 6.000e+00 7.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.990e+02 3.000e+00 2.100e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.466e+03 1.200e+01 1.000e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.470e+02 1.000e+00 2.600e+01 ...       nan       nan       nan]]


In [ ]:
print(y)

['Lentil, Apple, and Turkey Wrap '
 'Boudin Blanc Terrine with Red Onion Confit '
 'Potato and Fennel Soup Hodge ' ... 'Almond Brown Butter '
 'Spiced Chocolate Torte Wrapped in Chocolate Ribbons ' 'Herbed Olives ']


## Filtering based on Calories and Type of food

In [ ]:
recipes = pd.read_csv('Nutriv.csv')
def filter_by_cal(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['breakfast'] >= 1)]

filter_C =filter_by_cal(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)

# Step 5: Print out the recommended recipes
print(recommended_recipe.loc[:, 'title':'breakfast'])

                                                   title  calories  protein  \
6018   Super Green Smoothie Bowl With Matcha and Ginger      505.0     10.0   
17508                Egg and Avocado Breakfast Sandwich      445.0     17.0   

        fat  sodium  #cakeweek  #wasteless  22-minute meals  \
6018   39.0    34.0          0           0                0   
17508  24.0   449.0          0           0                0   

       3-ingredient recipes  30 days of groceries  ...  bon appétit  \
6018                      0                     0  ...            0   
17508                     0                     0  ...            1   

       bon app��tit  boston  bourbon  braise  bran  brandy  bread  \
6018              0       0        0       0     0       0      0   
17508             0       0        0       0     0       0      0   

       breadcrumbs  breakfast  
6018             0          1  
17508            0          1  

[2 rows x 71 columns]


In [ ]:
#@title lunch selector
repes = pd.read_csv('Nutriv.csv')

def filter_by_cal_lunch(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['lunch'] >= 1)]

filter_C =filter_by_cal_lunch(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)
recommended_recipe = recommended_recipe[['title','calories','protein','fat', 'lunch']]
# Step 5: Print out the recommended recipes
print(recommended_recipe)

                                                   title  calories  protein  \
18302                     Crab Cakes with Avocado Salad      462.0     19.0   
12251  Pan-Grilled Salmon on Toast with Scallion Mayo...     457.0     27.0   

        fat  lunch  
18302  25.0      1  
12251  32.0      1  


In [ ]:
def filter_by_cal_dinner(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['dinner'] >= 1)]

filter_C =filter_by_cal_dinner(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)
recommended_recipe = recommended_recipe[['title','calories','protein','fat', 'dinner']]
# Step 5: Print out the recommended recipes
print(recommended_recipe)

                                                   title  calories  protein  \
18509  Breaded Chicken Cutlets with Chunky Vegetable ...     531.0     66.0   
6572   Mustard-Maple Ham Steaks with Cider-Madeira Sa...     579.0     64.0   

        fat  dinner  
18509  14.0       1  
6572   19.0       1  


In [1]:
#@title Code 



In [3]:
import pandas as pd
import random

# Load the data into a pandas dataframe
df = pd.read_csv('Nutriv.csv')

# Define the range of the sum of the randomly selected values
min_sum = 1000
max_sum = 2000

# Select 5 random values from the numeric column
selected_values = []
while sum(selected_values) < min_sum or sum(selected_values) > max_sum:
    selected_values = random.sample(list(df['calories']), 5)

# Print the title values corresponding to the selected numeric values
for val in selected_values:
    print(df.loc[df['calories'] == val, 'title'].values[0])

Bacon Swiss Burgers with Tomato and Avocado 
Avocado and Grapefruit Salad 
Avocado, Shrimp, and Endive Salad 
Bavarian Cream with Raspberry Coulis 
Asparagus Soup with Basil Cream 
